### ISSUE TITLE
Missing use statements in compony-specific.inc

### ISSUE THREAD

**Issue by aimevp** [mathieuspil/Compony#15]
compony_library_info_alter is using undefined classes in it's try-catch logic when checking for a library yaml file (lines 28 and 30). To fix this it requires 2 extra use statements are required near the top of compony-specific.inc.

`use Drupal\Component\Serialization\Exception\InvalidDataTypeException;`
`use Drupal\Core\Asset\Exception\InvalidLibraryFileException;`

Grtzzz,
Aimé.

**Comment by mathieuspil** [comment]
Fixed!

**Comment by mathieuspil** [comment]
Thx Aimé!

Today and tomorrow I'll be iterating on this with new optional stuff (check other issues) :)

Some really cool stuff :)
